spring:
  devtools:
    restart:
      enabled: false # Mantener en false para despliegues estables
  application:
    name: one-core

  # Database configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 10000
      max-lifetime: 1800000      # 30 minutos
      connection-timeout: 30000
      leak-detection-threshold: 15000

  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: none # Correcto, Flyway maneja el schema
      multi_tenancy: SCHEMA
      multi_tenant_connection_provider: com.one.core.config.multitenancy.SchemaMultiTenantConnectionProvider
      tenant_identifier_resolver: com.one.core.config.multitenancy.JwtTenantIdentifierResolver
    show-sql: false


  flyway:
    enabled: true
    locations: classpath:db/migration/public # Solo para el schema public
    schemas: ${TENANT_SCHEMA:public}
    default-schema: ${TENANT_SCHEMA:public}

# Server configuration
server:
  port: 8080

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration.ms: 86400000
  issuer: one-core
  header: Authorization
  prefix: Bearer

# Logging
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: INFO
    com.one.core: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: WARN
    com.one.core.config.multitenancy.JwtTenantIdentifierResolver: INFO
    com.one.core.config.multitenancy.SchemaMultiTenantConnectionProvider: INFO

# Spring Boot Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none